DefaultContentLanguage = "en"
author = "username"
baseURL = "https://example.com"
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = "en"
theme = "tella"
title = "Tella"

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

mainSections = ['blog']

googleFonts = true

[params.logo]
alt = "Tella Logo"
main = "img/logo/logo.svg"

# The size parameter is the class name of tailwindcss
# https://tailwindcss.com/
size = "h-14"

[params.site]
name = "Tella"

[params.icon]
#If you want to use FontAwesome, set this parameter to true.
fontawesome = true

[params.homepage_meta_tags]
meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
meta_og_title = "Tella"
meta_og_type = "website"
meta_og_url = "https://tella.pages.dev"
meta_twitter_card = "summary_large_image"
meta_twitter_creator = "@username"
meta_twitter_site = "@username"

[menu]

[[menu.main]]
identifier = "products"
name = "Products"
url = "/products/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4

# Footer Menu
[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Github"
pre = "<i class='icon-github text-2xl'></i>"
url = "https://github.com/opera7133/tella"
weight = 2
